### ISSUE TITLE
Exception #0 (Exception): CURL can't connect: Could not resolve host: https

### ISSUE THREAD

**Issue by jnrbo** [pagseguro/magento2#105]
Está dando a seguinte exception:

```
1 exception(s):
Exception #0 (Exception): CURL can't connect: Could not resolve host: https

Exception #0 (Exception): CURL can't connect: Could not resolve host: https
#0 /var/www/html/vendor/pagseguro/pagseguro-php-sdk/source/Resources/Http.php(112): PagSeguro\Resources\Http->curlConnection('POST', 'https:///v2/ses...', 20, 'UTF-8', NULL)
#1 /var/www/html/vendor/pagseguro/pagseguro-php-sdk/source/Services/Session.php(52): PagSeguro\Resources\Http->post('https:///v2/ses...', NULL, 20, 'UTF-8')
#2 /var/www/html/app/code/UOL/PagSeguro/Helper/Library.php(160): PagSeguro\Services\Session::create(Object(PagSeguro\Domains\AccountCredentials))
#3 /var/www/html/app/code/UOL/PagSeguro/Model/PaymentConfigProvider.php(75): UOL\PagSeguro\Helper\Library->getSession()
#4 /var/www/html/app/code/Magento/Checkout/Model/CompositeConfigProvider.php(38): UOL\PagSeguro\Model\PaymentConfigProvider->getConfig()
#5 /var/www/html/app/code/Magento/Checkout/Block/Onepage.php(102): Magento\Checkout\Model\CompositeConfigProvider->getConfig()
#6 /var/www/html/app/code/Magento/Checkout/Block/Onepage.php(122): Magento\Checkout\Block\Onepage->getCheckoutConfig()
#7 /var/www/html/app/code/Magento/Checkout/view/frontend/templates/onepage.phtml(26): Magento\Checkout\Block\Onepage->getSerializedCheckoutConfig()
#8 /var/www/html/lib/internal/Magento/Framework/View/TemplateEngine/Php.php(59): include('/var/www/html/a...')
#9 /var/www/html/lib/internal/Magento/Framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage), '/var/www/html/a...', Array)
#10 /var/www/html/lib/internal/Magento/Framework/View/Element/Template.php(300): Magento\Framework\View\Element\Template->fetchView('/var/www/html/a...')
#11 /var/www/html/lib/internal/Magento/Framework/View/Element/AbstractBlock.php(667): Magento\Framework\View\Element\Template->_toHtml()
#12 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('checkout.root')
#14 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.root')
#15 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.root')
#16 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.root', true)
#17 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.root')
#18 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('content')
#19 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#20 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#21 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#22 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#23 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main')
#24 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#25 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#26 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', true)
#27 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main')
#28 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('columns')
#29 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#30 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#31 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#32 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#33 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('main.content')
#34 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#35 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#36 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#37 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#38 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#39 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#40 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#41 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#42 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#43 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('root')
#44 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#45 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(489): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#46 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#47 /var/www/html/lib/internal/Magento/Framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#48 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#49 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#50 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#51 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#52 /var/www/html/lib/internal/Magento/Framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#53 /var/www/html/lib/internal/Magento/Framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#54 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#55 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#56 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#57 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#58 /var/www/html/lib/internal/Magento/Framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#60 /var/www/html/lib/internal/Magento/Framework/App/Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#61 /var/www/html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#62 {main}
```

**Comment by thalessan** [comment]
Comigo acontece o mesmo problema, Magento 2.2.3. Tive que desativar o módulo para que o checkout funcionasse. Estou analisando a  causa.

**Comment by gcampedelli** [comment]
Tive o mesmo problema. Acabei mudando a configuração do servidor junto e do Varnish. 
Usei as seguintes configurações no Apache. 

<VirtualHost *:8080>
  ServerName localhost.com
  DocumentRoot /var/www/magento/pub
</VirtualHost>

<VirtualHost *:443>
    RequestHeader set X-Forwarded-Proto "https"
    ServerName localhost.com

    SSLEngine On
    SSLCertificateFile /etc/apache2/ssl/cert.crt
    SSLCertificateKeyFile /etc/apache2/ssl/cert.key

    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:80/
    ProxyPassReverse / http://127.0.0.1:80/
</VirtualHost>

Rolou

**Comment by thalessan** [comment]
Alguém conseguiu resolver o problema?

**Comment by gcampedelli** [comment]
Caro, eu consegui resolver o problema com as configurações descritas acima no servidor Apache2. 
Use a diretiva RequestHeader set X-Forwarded-Proto "https"
Não sei como é no Nginx. 
Também adicione a seguinte diretiva ao Varnish - 
-p feature=+esi_ignore_https \ 
No Daemon Opts, acima do Varnish secret file.

**Comment by albertobraschi** [comment]
Para mim apareceu esse erro mas acontece que o modulo ainda não havia sido configurado. 
Feito isso o checkout rodou correto.

**Comment by matheus0608** [comment]
no meu caso deu mesmo erro, mas resolvi colocando email e token.

**Comment by jerfeson** [comment]
Tive um problema muito parecido, e como sempre, o problema está entre a cadeira e o teclado.

No meu caso, em dado momento da lib do pagseguro, ele pega o Environment setado no código, e apesar de estar setado, ele não estava correto 💩

Sugiro sempre que possível debugar o código para pegar esses problemas.
